# -*- coding: utf-8 -*-
"""Embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vmAK9_Sq-J8toai2kryPMqSYQ6qgWpVO
"""

import torch, clip
from transformers import AutoTokenizer, AutoModel
from PIL import Image

clip_model, preprocess = clip.load("ViT-B/32")
xlm_tok = AutoTokenizer.from_pretrained("xlm-roberta-base")
xlm_model = AutoModel.from_pretrained("xlm-roberta-base")

def text_embed(text):
    tok = xlm_tok(text, return_tensors="pt", truncation=True)
    return xlm_model(**tok).last_hidden_state.mean(1)

def image_embed(img_path):
    img = preprocess(Image.open(img_path)).unsqueeze(0)
    return clip_model.encode_image(img)