# -*- coding: utf-8 -*-
"""Image-Text Alignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y9BFg0E-87_wrz5tD4CTobSrhK5PoEI3
"""

import torch
from sklearn.metrics.pairwise import cosine_similarity

def cosine_sim(a,b):
    return cosine_similarity(a.detach().numpy(), b.detach().numpy())[0][0]

def align(objects, sentences, img_emb):
    alignments=[]
    for s in sentences:
        t_emb = text_embed(s)
        score = cosine_sim(img_emb, t_emb)
        if score >= 0.6:
            alignments.append((s, score))
    return alignments