# -*- coding: utf-8 -*-
"""KG_visulization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SiFzpYk1y_bfWmSGOkTA1ma1kKLwPFAf
"""

from neo4j import GraphDatabase

class Neo4jKG:
    def __init__(self, user, password):
        self.driver = GraphDatabase.driver( auth=(user, password))

    def close(self):
        self.driver.close()

for h, r, t in text_triplets:
    kg.insert_text_triplet(h, r, t)

# Visual objects
for obj in detected_objects:
    kg.insert_visual_entity(
        label=obj["label"],
        bbox=obj["bbox"],
        conf=obj["conf"]
    )

# Multimodal alignments
for sent, score in alignments:
    for obj in detected_objects:
        kg.insert_visual_relation(sent, obj["label"], score)

kg.close()

