# -*- coding: utf-8 -*-
"""Object Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/133HTR0a4OGdTSwQear9Pr4-K1kgsR7eA
"""

pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
pip install easyocr paddleocr opencv-python

import easyocr, os, json

reader = easyocr.Reader(['hi','en'], gpu=False)
IMG_DIR = "data/images"
OUT = "outputs/ocr"
os.makedirs(OUT, exist_ok=True)

def run_ocr():
    store = {}
    for img in os.listdir(IMG_DIR):
        res = reader.readtext(os.path.join(IMG_DIR,img))
        store[img] = [{"text":t,"bbox":b,"conf":float(c)} for b,t,c in res]
        json.dump(store[img], open(f"{OUT}/{img}.json","w",encoding="utf-8"),
                  ensure_ascii=False, indent=2)
    return store

