# -*- coding: utf-8 -*-
"""POS_Tagging and Triplet Extraction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HlCg_6n48dAA_-LuTRsljx2ohBypxr1y
"""

import stanza
stanza.download("hi")
nlp=stanza.Pipeline("hi")

def extract_triplets(sentences):
    triplets=[]
    for s in sentences:
        doc=nlp(s)
        for sent in doc.sentences:
            sub=verb=obj=None
            for w in sent.words:
                if w.deprel=="nsubj": sub=w.text
                if w.upos=="VERB": verb=w.text
                if w.deprel in ["obj","obl"]: obj=w.text
            if sub and verb and obj:
                triplets.append((sub,verb,obj))
    return triplets