# -*- coding: utf-8 -*-
"""Visual_triplet .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d3ViS9EmeLi8OgopN0zcfg3mSMMJxdmd
"""

def make_visual_triplets(objects, alignments):
    triplets=[]
    for obj in objects:
        for sent,score in alignments:
            triplets.append((sent,"has_visual",obj["label"],score))
    return triplets